# Generated by Django 5.1.2 on 2024-12-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('transaccion', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('forma_pago', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('id_encargo', models.IntegerField()),
            ],
        ),
    ]
