# Generated by Django 5.1.2 on 2024-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_cliente',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='transaccion',
        ),
        migrations.AddField(
            model_name='compra',
            name='id_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
