# Generated by Django 5.1.2 on 2024-12-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_sucursal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
