# Generated by Django 5.1.2 on 2024-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('id_sucursal', models.IntegerField()),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
